// Cosa cercare su Amazon per riempire il catalogo: per ogni sottocategoria le parole chiave
// e le marche note ammesse. Per aggiungere una marca o una categoria basta modificare qui.

export type SearchGender = 'uomo' | 'donna' | 'unisex'

export interface CategoryPlan {
  /** id in src/config/categories.ts */
  category: string
  keywords: string
  brands: string[]
  genders: SearchGender[]
  /** Prezzo minimo in euro: esclude articoli sospetti o di bassa qualità */
  minPrice: number
  /** Reparto Amazon in cui cercare (di base Fashion) */
  searchIndex?: string
  /** Solo prodotti con buone recensioni (se Amazon le fornisce): stelle minime e numero minimo di voti */
  minRating?: number
  minReviews?: number
}

const BOTH: SearchGender[] = ['uomo', 'donna']
/** Prodotti per tutti: una sola ricerca, senza uomo/donna */
const TECH: SearchGender[] = ['unisex']
/** Gadget: per tutti, con almeno 4 stelle e 50 recensioni quando Amazon le fornisce */
const GADGET = { genders: TECH, minRating: 4, minReviews: 50 }
/** Beauty: uomo e donna, solo prodotti ben recensiti */
const BEAUTY = { searchIndex: 'Beauty', minRating: 4, minReviews: 50 }
/** Casa e animali: per tutti, solo prodotti ben recensiti */
const HOME = { genders: TECH, minRating: 4, minReviews: 50 }
/** Snack: come i gadget, nel reparto Alimentari */
const SNACK = { ...GADGET, searchIndex: 'GroceryAndGourmetFood' }

export const SEARCH_PLAN: CategoryPlan[] = [
  // Abbigliamento
  { category: 'tshirt', keywords: 't-shirt', minPrice: 12, genders: BOTH,
    brands: ['Tommy Hilfiger', 'Calvin Klein', 'Lacoste', 'Nike', 'adidas', 'Champion', "Levi's", 'BOSS'] },
  { category: 'felpe', keywords: 'felpa', minPrice: 20, genders: BOTH,
    brands: ['Champion', 'Nike', 'adidas', 'Tommy Hilfiger', 'Calvin Klein', 'The North Face', 'Puma', 'Carhartt'] },
  { category: 'maglioni', keywords: 'maglione', minPrice: 20, genders: BOTH,
    brands: ['Tommy Hilfiger', 'Ralph Lauren', 'GANT', 'Lacoste', 'Calvin Klein', 'Jack & Jones', 'Vero Moda', 'Only'] },
  { category: 'camicie', keywords: 'camicia', minPrice: 20, genders: BOTH,
    brands: ['Tommy Hilfiger', 'Ralph Lauren', 'GANT', "Levi's", 'Calvin Klein', 'BOSS', 'Lacoste', 'Guess'] },
  { category: 'pantaloni', keywords: 'pantaloni', minPrice: 20, genders: BOTH,
    brands: ["Levi's", 'Tommy Hilfiger', 'Carhartt', 'Dockers', 'Calvin Klein', 'Jack & Jones', 'Vero Moda', 'Only'] },
  { category: 'jeans', keywords: 'jeans', minPrice: 25, genders: BOTH,
    brands: ["Levi's", 'Pepe Jeans', 'Diesel', 'Wrangler', 'Tommy Jeans', 'Calvin Klein', 'Lee', 'Guess'] },
  { category: 'giacche', keywords: 'giacca', minPrice: 30, genders: BOTH,
    brands: ['The North Face', 'Columbia', 'Napapijri', 'Tommy Hilfiger', 'Superdry', "Levi's", 'Calvin Klein', 'Guess'] },
  { category: 'cappotti', keywords: 'cappotto', minPrice: 40, genders: BOTH,
    brands: ['Tommy Hilfiger', 'Calvin Klein', 'Guess', 'Vero Moda', 'Only', 'Superdry', 'Liu Jo', 'BOSS'] },
  { category: 'vestiti', keywords: 'vestito', minPrice: 20, genders: ['donna'],
    brands: ['Guess', 'Desigual', 'Liu Jo', 'Vero Moda', 'Only', 'Tommy Hilfiger', 'Calvin Klein', "Levi's"] },
  { category: 'sportivo', keywords: 'abbigliamento sportivo', minPrice: 15, genders: BOTH,
    brands: ['Nike', 'adidas', 'Puma', 'Under Armour', 'New Balance', 'ASICS', 'Reebok', 'Champion'] },
  // Scarpe
  { category: 'sneakers', keywords: 'sneakers', minPrice: 35, genders: BOTH,
    brands: ['Nike', 'adidas', 'New Balance', 'Puma', 'Converse', 'Vans', 'Reebok', 'Skechers', 'ASICS', 'Lacoste'] },
  { category: 'scarpe_eleganti', keywords: 'scarpe eleganti', minPrice: 40, genders: BOTH,
    brands: ['Clarks', 'Geox', 'Ecco', 'Tommy Hilfiger', 'Guess', 'Calvin Klein', 'Timberland', 'Lumberjack'] },
  { category: 'scarpe_sportive', keywords: 'scarpe running', minPrice: 40, genders: BOTH,
    brands: ['Nike', 'adidas', 'ASICS', 'New Balance', 'Brooks', 'Saucony', 'Mizuno', 'Puma'] },
  { category: 'stivali', keywords: 'stivali', minPrice: 50, genders: BOTH,
    brands: ['Dr. Martens', 'Timberland', 'UGG', 'Clarks', 'Geox', 'Guess', 'Tommy Hilfiger', 'Lumberjack'] },
  { category: 'sandali', keywords: 'sandali', minPrice: 20, genders: BOTH,
    brands: ['Birkenstock', 'Crocs', 'Havaianas', 'Teva', 'adidas', 'Nike', 'Geox', 'Ecco'] },
  // Accessori
  { category: 'occhiali', keywords: 'occhiali da sole', minPrice: 40, genders: BOTH,
    brands: ['Ray-Ban', 'Oakley', 'Persol', 'Carrera', 'Polaroid', 'Prada', 'Gucci', 'Vogue Eyewear'] },
  { category: 'cappellini', keywords: 'cappellino', minPrice: 12, genders: BOTH,
    brands: ['New Era', 'Nike', 'adidas', 'The North Face', 'Tommy Hilfiger', 'Calvin Klein', 'Carhartt', 'Lacoste'] },
  { category: 'orologi', keywords: 'orologio', minPrice: 30, genders: BOTH,
    brands: ['Casio', 'Seiko', 'Citizen', 'Tissot', 'Fossil', 'Michael Kors', 'Garmin', 'Daniel Wellington'] },
  { category: 'cinture', keywords: 'cintura', minPrice: 15, genders: BOTH,
    brands: ['Tommy Hilfiger', 'Calvin Klein', "Levi's", 'Guess', 'Lacoste', 'BOSS', 'Timberland', 'Ralph Lauren'] },
  { category: 'gioielli', keywords: 'gioielli', minPrice: 20, genders: BOTH,
    brands: ['Pandora', 'Swarovski', 'Morellato', 'Breil', 'Michael Kors', 'Guess', 'Fossil', 'Brosway'] },
  { category: 'portafogli', keywords: 'portafoglio', minPrice: 15, genders: BOTH,
    brands: ['Tommy Hilfiger', 'Calvin Klein', 'Guess', "Levi's", 'Lacoste', 'Fossil', 'Timberland', 'BOSS'] },
  { category: 'calze', keywords: 'calzini', minPrice: 8, genders: BOTH,
    brands: ['Nike', 'adidas', 'Puma', 'Tommy Hilfiger', 'Calvin Klein', "Levi's", 'Burlington', 'Falke'] },
  // Borse e zaini
  { category: 'zaini', keywords: 'zaino', minPrice: 25, genders: BOTH,
    brands: ['Eastpak', 'Invicta', 'The North Face', 'Herschel', 'Nike', 'adidas', 'Samsonite', 'Seven'] },
  { category: 'borse', keywords: 'borsa', minPrice: 30, genders: ['donna'],
    brands: ['Guess', 'Michael Kors', 'Liu Jo', 'Calvin Klein', 'Tommy Hilfiger', 'Desigual', 'Coccinelle', 'Furla'] },
  { category: 'borselli', keywords: 'borsello', minPrice: 20, genders: ['uomo'],
    brands: ['Calvin Klein', 'Tommy Hilfiger', 'Eastpak', 'The North Face', 'Guess', 'Lacoste', 'Nike', 'Napapijri'] },
  { category: 'borse_viaggio', keywords: 'borsa da viaggio', minPrice: 30, genders: BOTH,
    brands: ['Samsonite', 'American Tourister', 'Eastpak', 'The North Face', 'adidas', 'Nike', 'Herschel', 'Delsey'] },
  // Profumi (reparto Bellezza): prezzo minimo alto per evitare tester e imitazioni
  { category: 'profumi', keywords: 'eau de parfum', searchIndex: 'Beauty', minPrice: 30, genders: BOTH,
    brands: ['Dior', 'Armani', 'Yves Saint Laurent', 'Hugo Boss', 'Lancome', 'Dolce & Gabbana', 'Rabanne', 'Versace',
      'Calvin Klein', 'Prada', 'Valentino', 'Jean Paul Gaultier'] },
  // Sezione Tech: prodotti unisex
  { category: 'cuffie', keywords: 'cuffie wireless', searchIndex: 'Electronics', minPrice: 40, genders: TECH,
    brands: ['Sony', 'Bose', 'JBL', 'Sennheiser', 'Beats', 'Marshall', 'Audio-Technica', 'Apple'] },
  { category: 'auricolari', keywords: 'auricolari bluetooth', searchIndex: 'Electronics', minPrice: 30, genders: TECH,
    brands: ['Apple', 'Samsung', 'Sony', 'JBL', 'Bose', 'Jabra', 'Beats', 'Sennheiser', 'Nothing', 'Google'] },
  { category: 'casse', keywords: 'cassa bluetooth', searchIndex: 'Electronics', minPrice: 30, genders: TECH,
    brands: ['JBL', 'Bose', 'Marshall', 'Ultimate Ears', 'Sony', 'Anker', 'Bang & Olufsen', 'Sonos'] },
  { category: 'casse', keywords: 'soundbar', searchIndex: 'Electronics', minPrice: 60, genders: TECH,
    brands: ['Sonos', 'Bose', 'Samsung', 'LG', 'Sony', 'JBL', 'Yamaha'] },
  { category: 'smartphone', keywords: 'smartphone', searchIndex: 'Electronics', minPrice: 150, genders: TECH,
    brands: ['Apple', 'Samsung', 'Xiaomi', 'Google', 'Motorola', 'OnePlus', 'Honor', 'Nothing', 'Oppo'] },
  { category: 'smartwatch', keywords: 'smartwatch', searchIndex: 'Electronics', minPrice: 50, genders: TECH,
    brands: ['Apple', 'Samsung', 'Garmin', 'Huawei', 'Amazfit', 'Xiaomi', 'Google', 'Polar', 'Suunto'] },
  { category: 'tablet', keywords: 'tablet', searchIndex: 'Electronics', minPrice: 100, genders: TECH,
    brands: ['Apple', 'Samsung', 'Lenovo', 'Xiaomi', 'Amazon', 'Huawei', 'Microsoft'] },
  { category: 'videogiochi', keywords: 'videogioco', searchIndex: 'VideoGames', minPrice: 15, genders: TECH,
    brands: ['Nintendo', 'Sony', 'Electronic Arts', 'Ubisoft', 'Bandai Namco', 'Activision', 'Microsoft', 'Take-Two'] },
  { category: 'console', keywords: 'console', searchIndex: 'VideoGames', minPrice: 150, genders: TECH,
    brands: ['Nintendo', 'Sony', 'Microsoft', 'Valve'] },
  { category: 'console', keywords: 'Nintendo Switch', searchIndex: 'VideoGames', minPrice: 150, genders: TECH,
    brands: ['Nintendo'] },
  { category: 'console', keywords: 'PlayStation 5', searchIndex: 'VideoGames', minPrice: 150, genders: TECH,
    brands: ['Sony'] },
  { category: 'accessori_gaming', keywords: 'gaming', searchIndex: 'Electronics', minPrice: 25, genders: TECH,
    brands: ['Logitech', 'Razer', 'Corsair', 'SteelSeries', 'HyperX', 'Turtle Beach'] },
  { category: 'fotocamere', keywords: 'fotocamera', searchIndex: 'Electronics', minPrice: 80, genders: TECH,
    brands: ['GoPro', 'DJI', 'Canon', 'Sony', 'Fujifilm', 'Insta360', 'Nikon', 'Panasonic'] },
  { category: 'accessori_gaming', keywords: 'controller', searchIndex: 'VideoGames', minPrice: 25, genders: TECH,
    brands: ['Sony', 'Microsoft', 'Nintendo', '8BitDo', 'PowerA'] },
  { category: 'ereader', keywords: 'ebook reader', searchIndex: 'Electronics', minPrice: 60, genders: TECH,
    brands: ['Amazon', 'Kobo', 'PocketBook'] },
  { category: 'ereader', keywords: 'Kindle', searchIndex: 'Electronics', minPrice: 60, genders: TECH,
    brands: ['Amazon'] },
  { category: 'droni', keywords: 'drone', searchIndex: 'Electronics', minPrice: 100, genders: TECH,
    brands: ['DJI', 'Potensic', 'Ryze', 'Holy Stone'] },
  { category: 'droni', keywords: 'DJI mini', searchIndex: 'Electronics', minPrice: 100, genders: TECH,
    brands: ['DJI'] },
  { category: 'monitor', keywords: 'monitor', searchIndex: 'Electronics', minPrice: 90, genders: TECH,
    brands: ['Samsung', 'LG', 'ASUS', 'Dell', 'AOC', 'BenQ', 'MSI', 'Philips'] },
  { category: 'tastiere_mouse', keywords: 'tastiera mouse', searchIndex: 'Electronics', minPrice: 25, genders: TECH,
    brands: ['Logitech', 'Razer', 'Corsair', 'Keychron', 'SteelSeries', 'Microsoft', 'Apple'] },
  // Sezione Gadget: idee regalo e oggetti curiosi, solo marche note
  { category: 'gadget_cucina', keywords: 'gadget cucina', searchIndex: 'HomeAndKitchen', minPrice: 10, ...GADGET,
    brands: ['Joseph Joseph', 'OXO', 'Kikkerland', 'Fred', 'Tescoma', 'Lékué', 'Zyliss', 'Fizz Creations'] },
  { category: 'lampade', keywords: 'lampada', searchIndex: 'Lighting', minPrice: 15, ...GADGET,
    brands: ['Paladone', 'Govee', 'Philips', 'Fizz Creations', 'Twinkly', 'Nanoleaf', 'LEGO', 'Lumie'] },
  { category: 'tazze', keywords: 'tazza', searchIndex: 'HomeAndKitchen', minPrice: 10, ...GADGET,
    brands: ['Paladone', 'Fizz Creations', 'Thumbs Up', 'Pyramid International', 'Half Moon Bay', 'Ember', 'Stanley', 'Contigo'] },
  { category: 'giochi_tavolo', keywords: 'gioco da tavolo', searchIndex: 'ToysAndGames', minPrice: 12, ...GADGET,
    brands: ['Asmodee', 'Hasbro', 'Mattel', 'Ravensburger', 'Exploding Kittens', 'Big Potato', 'Cranio Creations', 'dV Giochi'] },
  { category: 'rompicapi', keywords: 'rompicapo', searchIndex: 'ToysAndGames', minPrice: 8, ...GADGET,
    brands: ["Rubik's", 'ThinkFun', 'Hanayama', 'GAN', 'MoYu', 'SmartGames', 'Ravensburger'] },
  { category: 'costruzioni', keywords: 'LEGO adulti', searchIndex: 'ToysAndGames', minPrice: 30, ...GADGET, brands: ['LEGO'] },
  { category: 'costruzioni', keywords: 'LEGO Icons', searchIndex: 'ToysAndGames', minPrice: 30, ...GADGET, brands: ['LEGO'] },
  { category: 'costruzioni', keywords: 'LEGO fiori', searchIndex: 'ToysAndGames', minPrice: 15, ...GADGET, brands: ['LEGO'] },
  { category: 'regali', keywords: 'regalo divertente', searchIndex: 'HomeAndKitchen', minPrice: 10, ...GADGET,
    brands: ['Paladone', 'Fizz Creations', 'Thumbs Up', 'Gift Republic', 'Kikkerland', 'Suck UK', 'Mustard', 'Luckies of London'] },
  { category: 'regali', keywords: 'gadget', searchIndex: 'ToysAndGames', minPrice: 10, ...GADGET,
    brands: ['Paladone', 'Fizz Creations', 'Thumbs Up', 'Kikkerland', 'Funko', 'Tamagotchi', 'Bandai'] },
  { category: 'gadget_tech', keywords: 'fotocamera istantanea', searchIndex: 'Electronics', minPrice: 50, ...GADGET,
    brands: ['Fujifilm', 'Polaroid', 'Kodak'] },
  { category: 'gadget_tech', keywords: 'stampante fotografica portatile', searchIndex: 'Electronics', minPrice: 40, ...GADGET,
    brands: ['Fujifilm', 'Kodak', 'Canon', 'HP', 'Polaroid'] },
  { category: 'gadget_tech', keywords: 'localizzatore bluetooth', searchIndex: 'Electronics', minPrice: 15, ...GADGET,
    brands: ['Apple', 'Tile', 'Samsung', 'Chipolo'] },
  { category: 'gadget_tech', keywords: 'mini proiettore', searchIndex: 'Electronics', minPrice: 100, ...GADGET,
    brands: ['XGIMI', 'Samsung', 'Anker', 'Nebula', 'Philips'] },
  // Sezione Snack: solo marche note
  { category: 'cioccolato', keywords: 'cioccolato', minPrice: 5, ...SNACK,
    brands: ['Lindt', 'Ferrero', 'Milka', 'Kinder', 'Novi', 'Venchi', 'Toblerone', 'Ritter Sport'] },
  { category: 'caramelle', keywords: 'caramelle', minPrice: 5, ...SNACK,
    brands: ['Haribo', 'Chupa Chups', 'Golia', 'Fini', 'Rossana', 'Mentos', 'Jelly Belly', 'Morositas'] },
  { category: 'biscotti', keywords: 'biscotti', minPrice: 5, ...SNACK,
    brands: ['Loacker', 'Mulino Bianco', 'Oreo', 'Lotus', 'Balocco', 'Gentilini', 'Galbusera', 'Pan di Stelle'] },
  { category: 'patatine', keywords: 'patatine', minPrice: 5, ...SNACK,
    brands: ['Pringles', 'San Carlo', 'Amica Chips', "Lay's", 'Doritos', 'Tyrrells', 'Pai', 'Crik Crok'] },
  { category: 'frutta_secca', keywords: 'frutta secca', minPrice: 5, ...SNACK,
    brands: ['Noberasco', 'Ventura', 'KoRo', 'Planters', 'Euro Company', 'Life'] },
  { category: 'frutta_secca', keywords: 'mandorle', minPrice: 5, ...SNACK,
    brands: ['Noberasco', 'Ventura', 'KoRo', 'Euro Company', 'Life', 'Blue Diamond'] },
  { category: 'frutta_secca', keywords: 'pistacchi', minPrice: 5, ...SNACK,
    brands: ['Noberasco', 'Ventura', 'KoRo', 'Euro Company', 'Life', 'Wonderful'] },
  { category: 'snack_proteici', keywords: 'barretta proteica', minPrice: 10, ...SNACK,
    brands: ['Myprotein', 'Prozis', 'foodspring', 'Barebells', 'Grenade', 'Enervit', 'Quest', 'PROTEIN WORKS'] },
  { category: 'snack_proteici', keywords: 'barretta proteica', minPrice: 10, ...SNACK,
    brands: ['Nutrend', 'Olimp', 'Weider', 'PowerBar', 'Optimum Nutrition', 'Bulk', 'Pro Action', 'Yamamoto Nutrition'] },
  { category: 'snack_proteici', keywords: 'snack proteico', minPrice: 8, ...SNACK,
    brands: ['Myprotein', 'Prozis', 'foodspring', 'Barebells', 'Lenny & Larry', 'Misfits', 'Fulfil', 'Ehrmann'] },
  { category: 'caffe_te', keywords: 'caffè', minPrice: 5, ...SNACK,
    brands: ['Lavazza', 'illy', 'Kimbo', 'Borbone', 'Segafredo', 'Starbucks', 'Nescafé'] },
  { category: 'caffe_te', keywords: 'tè', minPrice: 5, ...SNACK,
    brands: ['Twinings', 'Pompadour', 'Lipton', 'Yogi Tea', 'Sonnentor'] },
  // Sezione Beauty (i profumi sono più su)
  { category: 'skincare', keywords: 'crema viso', minPrice: 8, genders: BOTH, ...BEAUTY,
    brands: ['La Roche-Posay', 'CeraVe', 'Vichy', "L'Oréal Paris", 'Nivea', 'Eucerin', 'Garnier', 'The Ordinary', 'Clinique'] },
  { category: 'trucco', keywords: 'trucco', minPrice: 6, genders: ['donna'], ...BEAUTY,
    brands: ['Maybelline', "L'Oréal Paris", 'NYX', 'Rimmel', 'Max Factor', 'Benefit', 'Clinique', 'Estée Lauder', 'e.l.f.'] },
  { category: 'cura_capelli', keywords: 'shampoo', minPrice: 6, genders: BOTH, ...BEAUTY,
    brands: ["L'Oréal Professionnel", 'Kérastase', 'Olaplex', 'Pantene', 'Garnier', 'Moroccanoil', 'Davines'] },
  { category: 'styling_capelli', keywords: 'piastra capelli', minPrice: 25, genders: ['donna'], ...BEAUTY,
    brands: ['Dyson', 'ghd', 'Remington', 'BaByliss', 'Philips', 'Rowenta'] },
  { category: 'styling_capelli', keywords: 'asciugacapelli', minPrice: 25, genders: ['unisex'], ...BEAUTY,
    brands: ['Dyson', 'ghd', 'Remington', 'BaByliss', 'Philips', 'Rowenta', 'Braun'] },
  { category: 'rasatura', keywords: 'rasoio elettrico', minPrice: 25, genders: ['uomo'], ...BEAUTY,
    brands: ['Philips', 'Braun', 'Panasonic', 'Remington', 'Gillette'] },
  { category: 'rasatura', keywords: 'epilatore', minPrice: 25, genders: ['donna'], ...BEAUTY,
    brands: ['Braun', 'Philips', 'Remington', 'Panasonic'] },
  { category: 'rasatura', keywords: 'regolabarba', minPrice: 20, genders: ['uomo'], ...BEAUTY,
    brands: ['Philips', 'Braun', 'Panasonic', 'Remington', 'Wahl', 'BaByliss'] },
  { category: 'rasatura', keywords: 'luce pulsata', minPrice: 80, genders: ['donna'], ...BEAUTY,
    brands: ['Philips', 'Braun', 'Remington'] },
  // Sezione Casa
  { category: 'elettrodomestici', keywords: 'piccoli elettrodomestici cucina', searchIndex: 'HomeAndKitchen', minPrice: 30, ...HOME,
    brands: ['Smeg', 'KitchenAid', "De'Longhi", 'Kenwood', 'Ninja', 'Philips', 'Nespresso', 'Bialetti'] },
  { category: 'pentole', keywords: 'pentole', searchIndex: 'HomeAndKitchen', minPrice: 20, ...HOME,
    brands: ['Lagostina', 'Tefal', 'Le Creuset', 'WMF', 'Zwilling', 'Ballarini', 'Moneta', 'Victorinox'] },
  { category: 'design', keywords: 'oggetti design casa', searchIndex: 'HomeAndKitchen', minPrice: 20, ...HOME,
    brands: ['Alessi', 'Kartell', 'Guzzini', 'Umbra', 'Bitossi', 'Seletti', 'Stelton'] },
  { category: 'candele', keywords: 'candela profumata', searchIndex: 'HomeAndKitchen', minPrice: 10, ...HOME,
    brands: ['Yankee Candle', 'Millefiori Milano', 'Mr & Mrs Fragrance', 'Muha', 'Culti', 'Woodwick'] },
  { category: 'biancheria', keywords: 'copripiumino', searchIndex: 'HomeAndKitchen', minPrice: 25, ...HOME,
    brands: ['Caleffi', 'Bassetti', 'Zucchi', 'Somma', 'Gabel'] },
  { category: 'robot', keywords: 'robot aspirapolvere', searchIndex: 'HomeAndKitchen', minPrice: 120, ...HOME,
    brands: ['iRobot', 'Roborock', 'Dreame', 'Ecovacs', 'Xiaomi', 'Rowenta'] },
  { category: 'domotica', keywords: 'casa intelligente', searchIndex: 'Electronics', minPrice: 20, ...HOME,
    brands: ['Amazon', 'Google', 'Philips', 'Ring', 'TP-Link', 'Netatmo', 'Eufy'] },
  { category: 'domotica', keywords: 'lampadina smart', searchIndex: 'Lighting', minPrice: 15, ...HOME,
    brands: ['Philips Hue', 'Philips', 'TP-Link', 'Govee', 'Nanoleaf', 'Meross'] },
  { category: 'domotica', keywords: 'videocamera sorveglianza wifi', searchIndex: 'Electronics', minPrice: 25, ...HOME,
    brands: ['Ring', 'Eufy', 'TP-Link', 'Arlo', 'Blink', 'Netatmo', 'Reolink'] },
  { category: 'domotica', keywords: 'termostato smart', searchIndex: 'HomeAndKitchen', minPrice: 40, ...HOME,
    brands: ['Netatmo', 'tado', 'Google', 'Bticino', 'Honeywell'] },
  // Sezione Animali
  { category: 'guinzagli', keywords: 'pettorina cane', searchIndex: 'PetSupplies', minPrice: 12, ...HOME,
    brands: ['Julius-K9', 'Flexi', 'Ruffwear', 'Hunter', 'Trixie', 'Rabbitgoo'] },
  { category: 'cucce', keywords: 'cuccia', searchIndex: 'PetSupplies', minPrice: 20, ...HOME,
    brands: ['Ferplast', 'Trixie', 'Feandrea', 'Kerbl', 'Bedsure', 'Nobby'] },
  { category: 'tiragraffi', keywords: 'tiragraffi', searchIndex: 'PetSupplies', minPrice: 20, ...HOME,
    brands: ['Feandrea', 'Trixie', 'Ferplast', 'Kerbl', 'Nobby'] },
  { category: 'ciotole', keywords: 'fontanella gatto', searchIndex: 'PetSupplies', minPrice: 12, ...HOME,
    brands: ['Catit', 'PetSafe', 'Trixie', 'Ferplast', 'Xiaomi', 'Petlibro'] },
  { category: 'ciotole', keywords: 'ciotola cane', searchIndex: 'PetSupplies', minPrice: 8, ...HOME,
    brands: ['Trixie', 'Ferplast', 'Kong', 'Catit', 'PetSafe', 'Kerbl'] },
  { category: 'ciotole', keywords: 'distributore cibo automatico', searchIndex: 'PetSupplies', minPrice: 25, ...HOME,
    brands: ['PetSafe', 'Petlibro', 'Xiaomi', 'Catit', 'Cat Mate'] },
  { category: 'giochi_animali', keywords: 'gioco', searchIndex: 'PetSupplies', minPrice: 8, ...HOME,
    brands: ['Kong', 'Trixie', 'Chuckit!', 'Nerf Dog', 'Ferplast', 'Catit', 'Petstages'] },
  { category: 'premietti', keywords: 'snack', searchIndex: 'PetSupplies', minPrice: 8, ...HOME,
    brands: ['Pedigree', 'Purina', 'Whiskas', 'Dreamies', 'Royal Canin', 'Felix', 'Trixie'] },

  // Più prodotti per le sezioni non moda (10/10/2026): altre parole chiave, marche e categorie
  // Tech
  { category: 'cuffie', keywords: 'cuffie over ear', searchIndex: 'Electronics', minPrice: 40, genders: TECH,
    brands: ['Sony', 'Bose', 'Sennheiser', 'Beats', 'Marshall', 'Soundcore', 'Skullcandy', 'Philips'] },
  { category: 'auricolari', keywords: 'auricolari true wireless', searchIndex: 'Electronics', minPrice: 30, genders: TECH,
    brands: ['Soundcore', 'Xiaomi', 'Huawei', 'OnePlus', 'Technics', 'Skullcandy', 'Shokz', 'Bang & Olufsen'] },
  { category: 'smartphone', keywords: 'smartphone 5G', searchIndex: 'Electronics', minPrice: 150, genders: TECH,
    brands: ['Samsung', 'Xiaomi', 'Motorola', 'Honor', 'Realme', 'POCO', 'Redmi', 'Oppo', 'Vivo'] },
  { category: 'tablet', keywords: 'iPad', searchIndex: 'Electronics', minPrice: 100, genders: TECH, brands: ['Apple'] },
  { category: 'tablet', keywords: 'Galaxy Tab', searchIndex: 'Electronics', minPrice: 100, genders: TECH, brands: ['Samsung'] },
  { category: 'videogiochi', keywords: 'gioco PS5', searchIndex: 'VideoGames', minPrice: 15, genders: TECH,
    brands: ['Sony', 'Electronic Arts', 'Ubisoft', 'Bandai Namco', 'Warner Bros', 'Square Enix', 'Capcom', 'SEGA'] },
  { category: 'videogiochi', keywords: 'gioco Nintendo Switch', searchIndex: 'VideoGames', minPrice: 15, genders: TECH,
    brands: ['Nintendo', 'Ubisoft', 'Bandai Namco', 'SEGA', 'Electronic Arts', 'Square Enix', 'Capcom'] },
  { category: 'console', keywords: 'Xbox', searchIndex: 'VideoGames', minPrice: 150, genders: TECH, brands: ['Microsoft'] },
  { category: 'console', keywords: 'console portatile', searchIndex: 'Electronics', minPrice: 150, genders: TECH,
    brands: ['Valve', 'ASUS', 'Lenovo', 'Nintendo', 'MSI'] },
  { category: 'fotocamere', keywords: 'action cam', searchIndex: 'Electronics', minPrice: 80, genders: TECH,
    brands: ['GoPro', 'DJI', 'Insta360', 'AKASO'] },
  { category: 'fotocamere', keywords: 'fotocamera mirrorless', searchIndex: 'Electronics', minPrice: 300, genders: TECH,
    brands: ['Sony', 'Canon', 'Nikon', 'Fujifilm', 'Panasonic', 'OM System'] },
  { category: 'droni', keywords: 'drone con telecamera', searchIndex: 'Electronics', minPrice: 80, genders: TECH,
    brands: ['DJI', 'Potensic', 'Holy Stone', 'Ryze', 'Parrot'] },
  { category: 'monitor', keywords: 'monitor gaming', searchIndex: 'Electronics', minPrice: 120, genders: TECH,
    brands: ['Samsung', 'LG', 'ASUS', 'AOC', 'MSI', 'Acer', 'Gigabyte', 'BenQ'] },
  { category: 'tastiere_mouse', keywords: 'mouse wireless', searchIndex: 'Electronics', minPrice: 20, genders: TECH,
    brands: ['Logitech', 'Razer', 'Microsoft', 'Apple', 'Corsair', 'SteelSeries', 'HP'] },
  { category: 'smartwatch', keywords: 'fitness tracker', searchIndex: 'Electronics', minPrice: 30, genders: TECH,
    brands: ['Fitbit', 'Xiaomi', 'Garmin', 'Huawei', 'Amazfit', 'Samsung', 'Whoop'] },
  { category: 'notebook', keywords: 'notebook', searchIndex: 'Electronics', minPrice: 300, genders: TECH,
    brands: ['Apple', 'Lenovo', 'HP', 'ASUS', 'Acer', 'Dell', 'Microsoft', 'MSI', 'Samsung'] },
  { category: 'powerbank', keywords: 'power bank', searchIndex: 'Electronics', minPrice: 15, genders: TECH,
    brands: ['Anker', 'Belkin', 'UGREEN', 'Baseus', 'Xiaomi', 'Samsung', 'INIU'] },
  { category: 'powerbank', keywords: 'caricatore rapido', searchIndex: 'Electronics', minPrice: 15, genders: TECH,
    brands: ['Anker', 'Belkin', 'UGREEN', 'Apple', 'Samsung', 'Baseus'] },
  // Gadget
  { category: 'gadget_cucina', keywords: 'utensili cucina', searchIndex: 'HomeAndKitchen', minPrice: 10, ...GADGET,
    brands: ['Joseph Joseph', 'OXO', 'Tescoma', 'Zyliss', 'Microplane', 'Brabantia', 'Lékué', 'KitchenCraft'] },
  { category: 'lampade', keywords: 'luci LED', searchIndex: 'Lighting', minPrice: 15, ...GADGET,
    brands: ['Govee', 'Philips Hue', 'Twinkly', 'Nanoleaf', 'Paladone', 'Lexibook'] },
  { category: 'tazze', keywords: 'borraccia termica', searchIndex: 'HomeAndKitchen', minPrice: 15, ...GADGET,
    brands: ['Stanley', 'Contigo', '24Bottles', 'Chilly\'s', 'Thermos', 'Hydro Flask', 'Owala', 'S\'well'] },
  { category: 'giochi_tavolo', keywords: 'gioco di carte', searchIndex: 'ToysAndGames', minPrice: 8, ...GADGET,
    brands: ['Asmodee', 'Exploding Kittens', 'Mattel', 'Hasbro', 'Big Potato', 'dV Giochi', 'Ghenos Games', 'Oliphante'] },
  { category: 'giochi_tavolo', keywords: 'gioco di società', searchIndex: 'ToysAndGames', minPrice: 15, ...GADGET,
    brands: ['Ravensburger', 'Editrice Giochi', 'Clementoni', 'Hasbro', 'Cranio Creations', 'Asmodee', 'Days of Wonder'] },
  { category: 'costruzioni', keywords: 'LEGO Technic', searchIndex: 'ToysAndGames', minPrice: 30, ...GADGET, brands: ['LEGO'] },
  { category: 'costruzioni', keywords: 'LEGO Star Wars', searchIndex: 'ToysAndGames', minPrice: 25, ...GADGET, brands: ['LEGO'] },
  { category: 'costruzioni', keywords: 'LEGO Harry Potter', searchIndex: 'ToysAndGames', minPrice: 25, ...GADGET, brands: ['LEGO'] },
  { category: 'costruzioni', keywords: 'LEGO Architecture', searchIndex: 'ToysAndGames', minPrice: 25, ...GADGET, brands: ['LEGO'] },
  { category: 'puzzle', keywords: 'puzzle 1000 pezzi', searchIndex: 'ToysAndGames', minPrice: 10, ...GADGET,
    brands: ['Ravensburger', 'Clementoni', 'Educa', 'Schmidt', 'Trefl', 'Eurographics', 'Jumbo'] },
  { category: 'puzzle', keywords: 'puzzle 3D', searchIndex: 'ToysAndGames', minPrice: 15, ...GADGET,
    brands: ['Ravensburger', 'ROKR', 'Robotime', 'Clementoni', 'CubicFun'] },
  { category: 'collezionismo', keywords: 'Funko Pop', searchIndex: 'ToysAndGames', minPrice: 10, ...GADGET, brands: ['Funko'] },
  { category: 'collezionismo', keywords: 'action figure', searchIndex: 'ToysAndGames', minPrice: 15, ...GADGET,
    brands: ['Bandai', 'Hasbro', 'Mattel', 'McFarlane', 'Banpresto', 'Hot Wheels', 'Good Smile Company'] },
  { category: 'collezionismo', keywords: 'carte Pokémon', searchIndex: 'ToysAndGames', minPrice: 10, ...GADGET,
    brands: ['Pokémon', 'The Pokémon Company'] },
  { category: 'gadget_tech', keywords: 'cornice digitale', searchIndex: 'Electronics', minPrice: 40, ...GADGET,
    brands: ['Aura', 'Nixplay', 'Pix-Star', 'Amazon'] },
  { category: 'gadget_tech', keywords: 'giradischi', searchIndex: 'Electronics', minPrice: 60, ...GADGET,
    brands: ['Audio-Technica', 'Crosley', 'Victrola', 'Sony', 'Lenco', 'Pro-Ject'] },
  // Snack
  { category: 'cioccolato', keywords: 'cioccolatini', minPrice: 5, ...SNACK,
    brands: ['Lindt', 'Ferrero', 'Baci Perugina', 'Perugina', 'Caffarel', 'Godiva', 'Raffaello', 'Pocket Coffee'] },
  { category: 'caramelle', keywords: 'gomme da masticare', minPrice: 5, ...SNACK,
    brands: ['Vivident', 'Brooklyn', 'Mentos', 'Daygum', 'Happydent', 'Big Babol', 'Trident'] },
  { category: 'biscotti', keywords: 'wafer', minPrice: 5, ...SNACK,
    brands: ['Loacker', 'Balocco', 'Kinder', 'Manner', 'Crich', 'Galbusera', 'Ringo'] },
  { category: 'patatine', keywords: 'snack salati', minPrice: 5, ...SNACK,
    brands: ['San Carlo', 'Pringles', 'Fonzies', 'Cipster', 'Tuc', 'Taralli', 'Mulino Bianco', 'Pata'] },
  { category: 'snack_proteici', keywords: 'proteine whey', minPrice: 15, ...SNACK,
    brands: ['Myprotein', 'Prozis', 'Optimum Nutrition', 'foodspring', 'ESN', 'Bulk', 'Scitec Nutrition', 'Weider'] },
  { category: 'snack_proteici', keywords: 'crema spalmabile proteica', minPrice: 5, ...SNACK,
    brands: ['Myprotein', 'Prozis', 'foodspring', 'Bulk', 'Nutella', 'Barebells', 'Weider'] },
  { category: 'caffe_te', keywords: 'capsule caffè', minPrice: 8, ...SNACK,
    brands: ['Lavazza', 'Nespresso', 'Borbone', 'Kimbo', 'Starbucks', 'Nescafé Dolce Gusto', 'illy', 'L\'OR'] },
  { category: 'caffe_te', keywords: 'tisana', minPrice: 5, ...SNACK,
    brands: ['Yogi Tea', 'Pompadour', 'Twinings', 'Sonnentor', 'Bonomelli', 'Pukka'] },
  { category: 'bevande', keywords: 'energy drink', minPrice: 8, ...SNACK,
    brands: ['Red Bull', 'Monster', 'Burn', 'Rockstar', 'Prime'] },
  { category: 'bevande', keywords: 'bibite', minPrice: 8, ...SNACK,
    brands: ['Coca-Cola', 'Fanta', 'Sprite', 'San Pellegrino', 'Schweppes', 'Lemonsoda', 'Estathé', 'Lipton'] },
  // Beauty
  { category: 'skincare', keywords: 'siero viso', minPrice: 8, genders: BOTH, ...BEAUTY,
    brands: ['The Ordinary', 'La Roche-Posay', 'Vichy', "L'Oréal Paris", 'CeraVe', 'Garnier', 'Clinique', 'Estée Lauder'] },
  { category: 'skincare', keywords: 'crema solare viso', minPrice: 8, genders: ['unisex'], ...BEAUTY,
    brands: ['La Roche-Posay', 'Avène', 'ISDIN', 'Bioderma', 'Eucerin', 'Vichy', 'Nivea'] },
  { category: 'trucco', keywords: 'mascara', minPrice: 6, genders: ['donna'], ...BEAUTY,
    brands: ['Maybelline', "L'Oréal Paris", 'Lancôme', 'Benefit', 'Rimmel', 'Max Factor', 'Essence', 'Collistar'] },
  { category: 'trucco', keywords: 'rossetto', minPrice: 6, genders: ['donna'], ...BEAUTY,
    brands: ['Maybelline', "L'Oréal Paris", 'MAC', 'NYX', 'Rimmel', 'Clarins', 'Collistar', 'Deborah'] },
  { category: 'trucco', keywords: 'fondotinta', minPrice: 8, genders: ['donna'], ...BEAUTY,
    brands: ['Maybelline', "L'Oréal Paris", 'Estée Lauder', 'Max Factor', 'Clinique', 'NYX', 'Lancôme', 'Collistar'] },
  { category: 'cura_capelli', keywords: 'maschera capelli', minPrice: 6, genders: ['unisex'], ...BEAUTY,
    brands: ["L'Oréal Professionnel", 'Kérastase', 'Olaplex', 'Garnier', 'Moroccanoil', 'Davines', 'Pantene', 'Elvive'] },
  { category: 'styling_capelli', keywords: 'arricciacapelli', minPrice: 25, genders: ['donna'], ...BEAUTY,
    brands: ['Dyson', 'ghd', 'Remington', 'BaByliss', 'Philips', 'Rowenta', 'Shark'] },
  { category: 'rasatura', keywords: 'tagliacapelli', minPrice: 20, genders: ['uomo'], ...BEAUTY,
    brands: ['Philips', 'Braun', 'Wahl', 'Remington', 'BaByliss', 'Panasonic'] },
  { category: 'cura_corpo', keywords: 'crema corpo', minPrice: 6, genders: ['unisex'], ...BEAUTY,
    brands: ['Nivea', 'Neutrogena', 'Eucerin', 'CeraVe', 'Rituals', 'Palmer\'s', 'Bioderma', "L'Occitane"] },
  { category: 'cura_corpo', keywords: 'deodorante', minPrice: 5, genders: BOTH, ...BEAUTY,
    brands: ['Nivea', 'Dove', 'Rexona', 'Vichy', 'Axe', 'Borotalco', 'Mitchum', 'Old Spice'] },
  { category: 'cura_corpo', keywords: 'set regalo bagno', minPrice: 10, genders: ['unisex'], ...BEAUTY,
    brands: ['Rituals', "L'Occitane", 'Nivea', 'Dove', 'The Body Shop', 'Collistar'] },
  { category: 'spazzolini', keywords: 'spazzolino elettrico', minPrice: 20, genders: ['unisex'], ...BEAUTY,
    brands: ['Oral-B', 'Philips', 'Philips Sonicare', 'Panasonic', 'Waterpik', 'Xiaomi'] },
  { category: 'spazzolini', keywords: 'idropulsore', minPrice: 25, genders: ['unisex'], ...BEAUTY,
    brands: ['Waterpik', 'Oral-B', 'Philips', 'Panasonic'] },
  // Casa
  { category: 'elettrodomestici', keywords: 'frullatore', searchIndex: 'HomeAndKitchen', minPrice: 30, ...HOME,
    brands: ['Ninja', 'Philips', 'Kenwood', 'Smeg', 'KitchenAid', 'Braun', 'Moulinex', 'Nutribullet'] },
  { category: 'elettrodomestici', keywords: 'tostapane bollitore', searchIndex: 'HomeAndKitchen', minPrice: 25, ...HOME,
    brands: ['Smeg', "De'Longhi", 'Russell Hobbs', 'Kenwood', 'Philips', 'Bosch', 'Ariete'] },
  { category: 'pentole', keywords: 'coltelli cucina', searchIndex: 'HomeAndKitchen', minPrice: 20, ...HOME,
    brands: ['Zwilling', 'WMF', 'Victorinox', 'Wüsthof', 'Global', 'Sanelli', 'Tescoma'] },
  { category: 'pentole', keywords: 'padella antiaderente', searchIndex: 'HomeAndKitchen', minPrice: 15, ...HOME,
    brands: ['Tefal', 'Ballarini', 'Lagostina', 'Moneta', 'Pensofal', 'Tognana', 'Aeternum'] },
  { category: 'macchine_caffe', keywords: 'macchina caffè', searchIndex: 'HomeAndKitchen', minPrice: 40, ...HOME,
    brands: ["De'Longhi", 'Nespresso', 'Philips', 'Krups', 'Smeg', 'Lavazza', 'Bialetti', 'Sage'] },
  { category: 'macchine_caffe', keywords: 'moka', searchIndex: 'HomeAndKitchen', minPrice: 15, ...HOME,
    brands: ['Bialetti', 'Alessi', 'Pedrini', 'Lagostina'] },
  { category: 'friggitrici', keywords: 'friggitrice ad aria', searchIndex: 'HomeAndKitchen', minPrice: 40, ...HOME,
    brands: ['Ninja', 'Philips', 'COSORI', 'Tefal', "De'Longhi", 'Moulinex', 'Instant', 'Russell Hobbs'] },
  { category: 'design', keywords: 'vaso decorativo', searchIndex: 'HomeAndKitchen', minPrice: 15, ...HOME,
    brands: ['Kartell', 'Seletti', 'Bitossi', 'Alessi', 'Umbra', 'Guzzini', 'Villeroy & Boch', 'Thun'] },
  { category: 'design', keywords: 'orologio da parete', searchIndex: 'HomeAndKitchen', minPrice: 20, ...HOME,
    brands: ['Umbra', 'Karlsson', 'Alessi', 'Kartell', 'Seletti', 'Lowell'] },
  { category: 'candele', keywords: 'diffusore ambiente', searchIndex: 'HomeAndKitchen', minPrice: 10, ...HOME,
    brands: ['Millefiori Milano', 'Yankee Candle', 'Culti', 'Mr & Mrs Fragrance', 'Muha', 'Rituals', 'Ipuro'] },
  { category: 'biancheria', keywords: 'asciugamani', searchIndex: 'HomeAndKitchen', minPrice: 15, ...HOME,
    brands: ['Caleffi', 'Bassetti', 'Zucchi', 'Gabel', 'Somma', 'Svad Dondi'] },
  { category: 'biancheria', keywords: 'plaid coperta', searchIndex: 'HomeAndKitchen', minPrice: 15, ...HOME,
    brands: ['Caleffi', 'Bassetti', 'Zucchi', 'Gabel', 'Bedsure', 'Somma'] },
  { category: 'robot', keywords: 'robot lavapavimenti', searchIndex: 'HomeAndKitchen', minPrice: 150, ...HOME,
    brands: ['Roborock', 'Dreame', 'Ecovacs', 'iRobot', 'Xiaomi', 'Narwal', 'Eufy'] },
  { category: 'domotica', keywords: 'altoparlante intelligente', searchIndex: 'Electronics', minPrice: 20, ...HOME,
    brands: ['Amazon', 'Google', 'Sonos', 'Apple', 'Bose'] },
  { category: 'domotica', keywords: 'presa intelligente', searchIndex: 'Electronics', minPrice: 10, ...HOME,
    brands: ['TP-Link', 'Meross', 'Shelly', 'Amazon', 'Eve', 'Tapo'] },
  { category: 'aspirapolvere', keywords: 'scopa elettrica senza fili', searchIndex: 'HomeAndKitchen', minPrice: 60, ...HOME,
    brands: ['Dyson', 'Rowenta', 'Bosch', 'Samsung', 'Hoover', 'Shark', 'Dreame', 'Philips', 'Xiaomi'] },
  { category: 'aspirapolvere', keywords: 'lavapavimenti', searchIndex: 'HomeAndKitchen', minPrice: 80, ...HOME,
    brands: ['Vileda', 'Tineco', 'Dreame', 'Bissell', 'Polti', 'Karcher', 'Philips'] },
  { category: 'aspirapolvere', keywords: 'aspirabriciole', searchIndex: 'HomeAndKitchen', minPrice: 25, ...HOME,
    brands: ['Dyson', 'Black+Decker', 'Bosch', 'Rowenta', 'Shark', 'Philips'] },
  // Animali
  { category: 'guinzagli', keywords: 'guinzaglio', searchIndex: 'PetSupplies', minPrice: 8, ...HOME,
    brands: ['Flexi', 'Julius-K9', 'Ruffwear', 'Hunter', 'Trixie', 'Kong', 'Ferplast'] },
  { category: 'guinzagli', keywords: 'collare', searchIndex: 'PetSupplies', minPrice: 8, ...HOME,
    brands: ['Hunter', 'Trixie', 'Ruffwear', 'Julius-K9', 'Ferplast', 'Tractive'] },
  { category: 'cucce', keywords: 'cuscino cane', searchIndex: 'PetSupplies', minPrice: 15, ...HOME,
    brands: ['Bedsure', 'Feandrea', 'Trixie', 'Ferplast', 'Nobby', 'Kerbl', 'Lionto'] },
  { category: 'cucce', keywords: 'cuccia gatto', searchIndex: 'PetSupplies', minPrice: 15, ...HOME,
    brands: ['Feandrea', 'Trixie', 'Ferplast', 'Bedsure', 'Kerbl', 'Nobby'] },
  { category: 'giochi_animali', keywords: 'gioco gatto', searchIndex: 'PetSupplies', minPrice: 6, ...HOME,
    brands: ['Catit', 'Trixie', 'Petstages', 'Kong', 'Ferplast', 'Nobby'] },
  { category: 'giochi_animali', keywords: 'gioco interattivo cane', searchIndex: 'PetSupplies', minPrice: 8, ...HOME,
    brands: ['Kong', 'Outward Hound', 'Trixie', 'Chuckit!', 'Nina Ottosson', 'Nerf Dog'] },
  { category: 'premietti', keywords: 'snack gatto', searchIndex: 'PetSupplies', minPrice: 5, ...HOME,
    brands: ['Dreamies', 'Felix', 'Whiskas', 'Catisfactions', 'Gourmet', 'Purina'] },
  { category: 'cibo_cani', keywords: 'crocchette cane', searchIndex: 'PetSupplies', minPrice: 10, ...HOME,
    brands: ['Royal Canin', 'Purina', 'Monge', "Hill's", 'Almo Nature', 'Farmina', 'Oasy', 'Pedigree'] },
  { category: 'cibo_cani', keywords: 'umido cane', searchIndex: 'PetSupplies', minPrice: 8, ...HOME,
    brands: ['Cesar', 'Pedigree', 'Rocco', 'Monge', 'Almo Nature', 'Purina', 'Royal Canin'] },
  { category: 'cibo_gatti', keywords: 'crocchette gatto', searchIndex: 'PetSupplies', minPrice: 10, ...HOME,
    brands: ['Royal Canin', 'Purina', 'Monge', "Hill's", 'Almo Nature', 'Farmina', 'Oasy', 'Whiskas'] },
  { category: 'cibo_gatti', keywords: 'umido gatto', searchIndex: 'PetSupplies', minPrice: 8, ...HOME,
    brands: ['Felix', 'Gourmet', 'Sheba', 'Whiskas', 'Schesir', 'Almo Nature', 'Monge', 'Applaws'] },
  { category: 'lettiere', keywords: 'lettiera gatto', searchIndex: 'PetSupplies', minPrice: 8, ...HOME,
    brands: ['Catsan', "Cat's Best", 'Ever Clean', 'Sanicat', 'Vitakraft', 'Trixie', 'Ferplast', 'Catit'] },
  { category: 'trasportini', keywords: 'trasportino', searchIndex: 'PetSupplies', minPrice: 15, ...HOME,
    brands: ['Ferplast', 'Trixie', 'Petmate', 'Catit', 'Feandrea', 'Stefanplast', 'Kerbl'] },
]

/** Confronto tollerante tra marche ("TOMMY HILFIGER" = "Tommy Hilfiger", "Levi's" = "Levis"). */
export const normalizeBrand = (b: string) =>
  b
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '')
